import json, re
import logging
from channels.generic.websocket import AsyncWebsocketConsumer
from asgiref.sync import sync_to_async
from .models import BarberQueue, Barbero
from .utils import safe_channel_name

logger = logging.getLogger(__name__)

class QueueConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        try:
            # 1. Obtener y validar barber_id
            self.barber_id = str(self.scope['url_route']['kwargs']['barber_id'])
            cleaned_barber_id = safe_channel_name(self.barber_id)
            
            if not cleaned_barber_id:
                logger.error(f"Invalid barber_id: {self.barber_id}")
                await self.close(code=4001)
                return
            if len(self.room_group_name) > 100:
                self.room_group_name = self.room_group_name[:100]

        # Verifica que el group name sea válido
            if not re.match(r'^[a-zA-Z0-9\-_\.]+$', self.room_group_name):
                raise ValueError(f"Invalid group name: {self.room_group_name}")

            # 2. Crear nombre de grupo seguro
            self.room_group_name = f'queue_{cleaned_barber_id}'
            
            # 3. Validar channel_name automático
            if not hasattr(self, 'channel_name') or not isinstance(self.channel_name, str):
                logger.error("Invalid channel_name generated by Channels")
                await self.close(code=4002)
                return

            logger.info(f"Connecting to group: {self.room_group_name}")
            
            # 4. Unirse al grupo
            await self.channel_layer.group_add(
                self.room_group_name,
                self.channel_name
            )
            await self.accept()
            
            # 5. Enviar estado inicial
            await self.send_initial_state()

        except KeyError:
            logger.error("Missing barber_id in URL route")
            await self.close(code=4000)
        except Exception as e:
            logger.error(f"Connection error: {str(e)}", exc_info=True)
            await self.close(code=4003)

    async def send_initial_state(self):
        """Envía el estado inicial de la cola al cliente"""
        try:
            barbero = await sync_to_async(Barbero.objects.get)(id=self.barber_id)
            queue = await sync_to_async(BarberQueue.get_or_create_queue_for_barber)(barbero)
            
            await self.send(text_data=json.dumps({
                'type': 'queue_update',
                'barber_id': self.barber_id,
                'number': queue.current_number,
                'last_issued_number': queue.last_issued_number
            }))
        except Barbero.DoesNotExist:
            logger.warning(f"Barbero {self.barber_id} not found")
            await self.send(text_data=json.dumps({
                'type': 'error',
                'message': 'Barbero no encontrado'
            }))
        except Exception as e:
            logger.error(f"Error sending initial state: {str(e)}")
            await self.close(code=4004)

    async def disconnect(self, close_code):
        if hasattr(self, 'room_group_name'):
            await self.channel_layer.group_discard(
                self.room_group_name,
                self.channel_name
            )
        logger.info(f"Disconnected with code {close_code}")

    async def queue_update(self, event):
        """Maneja actualizaciones de cola enviadas al grupo"""
        try:
            await self.send(text_data=json.dumps({
                'type': 'queue_update',
                'barber_id': event['barber_id'],
                'number': event['number'],
                'last_issued_number': event.get('last_issued_number', 0)
            }))
        except Exception as e:
            logger.error(f"Error sending update: {str(e)}")

    async def receive(self, text_data):
        """Maneja mensajes recibidos del cliente"""
        try:
            data = json.loads(text_data)
            if data.get('type') == 'reset_counter':
                await self.reset_queue(data.get('barber_id'))
        except json.JSONDecodeError:
            logger.error("Invalid JSON received")
        except Exception as e:
            logger.error(f"Error processing message: {str(e)}")

    async def reset_queue(self, barber_id):
        """Reinicia la cola y notifica al grupo"""
        if not barber_id:
            return
            
        try:
            safe_id = safe_channel_name(barber_id)
            if not safe_id:
                raise ValueError("Invalid barber_id")
                
            barbero = await sync_to_async(Barbero.objects.get)(id=barber_id)
            queue = await sync_to_async(BarberQueue.get_or_create_queue_for_barber)(barbero)
            await sync_to_async(queue.reset_queue)()
            
            await self.channel_layer.group_send(
                f'queue_{safe_id}',
                {
                    'type': 'queue_update',
                    'barber_id': barber_id,
                    'number': queue.current_number,
                    'last_issued_number': queue.last_issued_number
                }
            )
        except Exception as e:
            logger.error(f"Error resetting queue: {str(e)}")