# Generated by Django 5.2.1 on 2025-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberqueue',
            name='last_issued_number',
            field=models.IntegerField(default=0, verbose_name='Último Número de Ticket Emitido'),
        ),
        migrations.AlterField(
            model_name='barberqueue',
            name='current_number',
            field=models.IntegerField(default=0, verbose_name='Número Actual Siendo Atendido'),
        ),
    ]
